projects:
  BiddingService-Api-test-ap-south-1:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/queries/bid.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql/queries
        region: ap-south-1
        apiId: zekfdb7sffedved2u3nz6tat2u
        maxDepth: 2
extensions:
  amplify:
    version: 3
